name: Tests

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:5.0-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        run: pwsh -File ./Run-UnitTests.ps1
